### ISSUE TITLE
Fix GyroIO reset() method

### ISSUE THREAD

**Issue by Yxhej** [SciBorgs/Crescendo-2024#10]
Currently, GyroIO's `reset()` method has no effect on the actual heading reported by our NavX2-MXP. When called in `Drive`, it simply does not reset the heading despite DriverStation reporting a reset taking place. However, upon creating the NavX directly in Drive, calling `reset()` does zero the heading, like it should. Current cause of this behavior is unknown.

We've determined a few things in testing:
- button bindings work as intended
- the `runOnce` command factory works as intended
- the NavX was not calibrating while the robot was running, which would typically disable a heading reset

**Comment by anglesideangle** [comment]
I don't think this is needed anymore now that we're using a pose estimator with apriltags
