### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by anglesideangle** [SciBorgs/Crescendo-2024#37]
There is currently inconsistent naming of getter methods in our code. Some are named `getValue()` and other are named `value()`. The latter is nicer, so we want to switch all of our getters to use that naming convention. You can use vscode global search to find all instances of the word "get"

Additionally, a lot of our interfaces contain unnecessary accessibility modifiers
```java
public interface Example {
    public double value();
    public String str();
}
```
These `public`s are not necessary because everything in an interface is implicitly public.

**Comment by jonahk4** [comment]
Finished
